### ISSUE TITLE
`slice_block` should allow for `List[int]` as parameter

### ISSUE THREAD

**Issue by PicoCentauri** [lab-cosmo/metatensor#187]
The  function is super useful when sub selecting from a `TensorBlock`. It currently only takes a `Labels` instance.

https://github.com/lab-cosmo/equistore/blob/7d271dca094fd2aa9d86fa238b9d28dc73e4f257/python/src/equistore/operations/slice.py#L91-L95

An useful addition is to also allow a list of `integer. This basically boils down to changing these lines directly taking the provided list for the selection.

https://github.com/lab-cosmo/equistore/blob/7d271dca094fd2aa9d86fa238b9d28dc73e4f257/python/src/equistore/operations/slice.py#L204-L210

**Comment by PicoCentauri** [comment]
Good question. I would not introduce and extra argument because `labels` and `indices` are exclusive. If you provide both to the same at the same time it should be an error. 

The name `labels` is not clear enough that you can also provide integers in a list. What about renaming `labels` to `choices` or something similar?

**Comment by jwa7** [comment]
Hmm I'm not sure I like that - IMO I think `labels` should be kept as the 'usual' functionality and because the `List[int]` is more of an advanced feature I think it would make more sense to have it as a separate arg, but you are right that this should raise an error if both are passed.

For me passing `List[int]` is more of a speedy option to slice with, similar in vein to the `unsafe=True` flag that we've talked about - i.e. it comes with risks but can make things faster. In this case I think it makes sense to have it as a separate arg.

Thoughts @Luthaf ?
