### ISSUE TITLE
Enforce the same `device/dtype` when constructing `metatensor.torch.TensorBlock/TensorMap`s

### ISSUE THREAD

**Issue by frostedoyster** [lab-cosmo/metatensor#370]
Not doing so would most likely result in operations failing due to device or type mismatches

**Comment by Luthaf** [comment]
I think the checks should be done in the metatensor-torch C++ code, since the same issue can happen when creating data from C++.

**Comment by Luthaf** [comment]
> I agree, devices should be consistent at creation time. I can't see use cases to have different pieces on different devices.

@ceriottm in https://github.com/lab-cosmo/metatensor/issues/413#issuecomment-1789830279

> Perhaps to distribute calculations. Some blocks could live in cuda:0, others in cuda:1, and so on

> @frostedoyster in https://github.com/lab-cosmo/metatensor/issues/413#issuecomment-1790135849


---

I could see a point for different blocks to be on different variations on the same kind of device (i.e. `cuda:0`/`cuda:1`), but not on different kind of devices. The keys would then have to be on the same kind of device as well.

**Comment by ceriottm** [comment]
Should we enforce consistency between data and metadata  of a block, and let complete freedom between different blocks in the same map?

**Comment by Luthaf** [comment]
Thinking a bit more about this, I don't think we can have different devices for different `block.values`, because `keys_to_xxx` requires all the data to be on the same device.

For distributed calculations, I feel like it would be better to distribute over samples instead of blocks, and then use separate TensorMap on separate devices. Can you see a point where splitting distributed calculations over samples would not work?

**Comment by Luthaf** [comment]
Fixed by #414
