### ISSUE TITLE
Reduction operations are broken due to naming mismatch

### ISSUE THREAD

**Issue by ceriottm** [lab-cosmo/metatensor#388]
It appears that `sum_over_samples` is broken because on the rust side we name a member property `sample_names`, but on the python side we use everywhere `samples_names`. We need consistency.
I am happy to do the renaming but would like everyone to agree on the preferred form. 

`sample_names` somehow sounds better to me, but `samples_names` is closer to the fact this is a shortcut for block.samples.names. 

Thoughts?

**Comment by ceriottm** [comment]
It might actually be rascaline being on an older version of metatensor - still, I think it'd be useful for the future to be consistent. I'll open a PR that renames the rust objects to be consistent with the naming scheme we use on the python side.

**Comment by Luthaf** [comment]
For reference, the names where changed in https://github.com/lab-cosmo/metatensor/pull/348, which rascaline should pull in since https://github.com/lab-cosmo/metatensor/pull/348. You might want to re-install both metatensor-operations and rascaline to be sure you have everything at the latest version.

**Comment by Luthaf** [comment]
Fixed by #399
